#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleManager.h"
#include "Framework/Commands/UICommandList.h"
#include "Framework/MultiBox/MultiBoxBuilder.h"

// Module API macro - auto-generated by UBT based on module name
#ifndef TRIPSITTERUE_API
    #define TRIPSITTERUE_API DLLEXPORT
#endif

class FExtender;

class TRIPSITTERUE_API FTripSitterUEModule : public IModuleInterface
{
public:
    virtual void StartupModule() override;
    virtual void ShutdownModule() override;

private:
    void AddMenuExtension(FMenuBuilder& MenuBuilder);
    void OpenTripSitterWindow();

    TSharedPtr<FExtender> MenuExtender;
};
